#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



public partial class DB_Library : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBook(Book instance);
  partial void UpdateBook(Book instance);
  partial void DeleteBook(Book instance);
  partial void InsertBook_copy(Book_copy instance);
  partial void UpdateBook_copy(Book_copy instance);
  partial void DeleteBook_copy(Book_copy instance);
  partial void InsertRead_copy(Read_copy instance);
  partial void UpdateRead_copy(Read_copy instance);
  partial void DeleteRead_copy(Read_copy instance);
  partial void InsertReader(Reader instance);
  partial void UpdateReader(Reader instance);
  partial void DeleteReader(Reader instance);
  partial void InsertRoom(Room instance);
  partial void UpdateRoom(Room instance);
  partial void DeleteRoom(Room instance);
  partial void InsertStatus(Status instance);
  partial void UpdateStatus(Status instance);
  partial void DeleteStatus(Status instance);
  #endregion
	
	public DB_Library(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DB_Library(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DB_Library(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DB_Library(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Book> Books
	{
		get
		{
			return this.GetTable<Book>();
		}
	}
	
	public System.Data.Linq.Table<Book_copy> Book_copies
	{
		get
		{
			return this.GetTable<Book_copy>();
		}
	}
	
	public System.Data.Linq.Table<Read_copy> Read_copies
	{
		get
		{
			return this.GetTable<Read_copy>();
		}
	}
	
	public System.Data.Linq.Table<Reader> Readers
	{
		get
		{
			return this.GetTable<Reader>();
		}
	}
	
	public System.Data.Linq.Table<Room> Rooms
	{
		get
		{
			return this.GetTable<Room>();
		}
	}
	
	public System.Data.Linq.Table<Status> Status
	{
		get
		{
			return this.GetTable<Status>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.count_books")]
	[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
	public int Count_books([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_reader, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> a)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_reader, a);
		a = ((System.Nullable<int>)(result.GetParameterValue(1)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.count_readers")]
	[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
	public int Count_readers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> a)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), a);
		a = ((System.Nullable<int>)(result.GetParameterValue(0)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.find_cipher")]
	[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
	public int Find_cipher([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> cipher)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, cipher);
		cipher = ((System.Nullable<int>)(result.GetParameterValue(1)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.find_readers_book")]
	public ISingleResult<Find_readers_bookResult> Find_readers_book([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_reader)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_reader);
		return ((ISingleResult<Find_readers_bookResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_diagramobjects", IsComposable=true)]
	[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
	public System.Nullable<int> Fn_diagramobjects()
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_alterdiagram")]
	[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
	public int Sp_alterdiagram([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string diagramname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> owner_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> version, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary definition)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diagramname, owner_id, version, definition);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_creatediagram")]
	[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
	public int Sp_creatediagram([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string diagramname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> owner_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> version, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary definition)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diagramname, owner_id, version, definition);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dropdiagram")]
	[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
	public int Sp_dropdiagram([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string diagramname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> owner_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diagramname, owner_id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_helpdiagramdefinition")]
	public ISingleResult<Sp_helpdiagramdefinitionResult> Sp_helpdiagramdefinition([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string diagramname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> owner_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diagramname, owner_id);
		return ((ISingleResult<Sp_helpdiagramdefinitionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_helpdiagrams")]
	public ISingleResult<Sp_helpdiagramsResult> Sp_helpdiagrams([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string diagramname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> owner_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diagramname, owner_id);
		return ((ISingleResult<Sp_helpdiagramsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_renamediagram")]
	[return: global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")]
	public int Sp_renamediagram([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string diagramname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> owner_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(128)")] string new_diagramname)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), diagramname, owner_id, new_diagramname);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.book")]
public partial class Book : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _Cipher;
	
	private string _Title;
	
	private string _Author;
	
	private System.Nullable<System.DateTime> _Data_publish;
	
	private EntitySet<Book_copy> _Book_copies;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCipherChanging(int value);
    partial void OnCipherChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnData_publishChanging(System.Nullable<System.DateTime> value);
    partial void OnData_publishChanged();
    #endregion
	
	public Book()
	{
		this._Book_copies = new EntitySet<Book_copy>(new Action<Book_copy>(this.attach_Book_copies), new Action<Book_copy>(this.detach_Book_copies));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cipher", Storage="_Cipher", DbType="Int NOT NULL")]
	public int Cipher
	{
		get
		{
			return this._Cipher;
		}
		set
		{
			if ((this._Cipher != value))
			{
				this.OnCipherChanging(value);
				this.SendPropertyChanging();
				this._Cipher = value;
				this.SendPropertyChanged("Cipher");
				this.OnCipherChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="title", Storage="_Title", DbType="VarChar(200)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="author", Storage="_Author", DbType="VarChar(200)")]
	public string Author
	{
		get
		{
			return this._Author;
		}
		set
		{
			if ((this._Author != value))
			{
				this.OnAuthorChanging(value);
				this.SendPropertyChanging();
				this._Author = value;
				this.SendPropertyChanged("Author");
				this.OnAuthorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_publish", Storage="_Data_publish", DbType="Date")]
	public System.Nullable<System.DateTime> Data_publish
	{
		get
		{
			return this._Data_publish;
		}
		set
		{
			if ((this._Data_publish != value))
			{
				this.OnData_publishChanging(value);
				this.SendPropertyChanging();
				this._Data_publish = value;
				this.SendPropertyChanged("Data_publish");
				this.OnData_publishChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__book_copy__ID_bo__59FA5E80", Storage="_Book_copies", ThisKey="Id", OtherKey="Id_book", DeleteRule="NO ACTION")]
	public EntitySet<Book_copy> Book_copies
	{
		get
		{
			return this._Book_copies;
		}
		set
		{
			this._Book_copies.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Book_copies(Book_copy entity)
	{
		this.SendPropertyChanging();
		entity.Book = this;
	}
	
	private void detach_Book_copies(Book_copy entity)
	{
		this.SendPropertyChanging();
		entity.Book = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.book_copy")]
public partial class Book_copy : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _Status;
	
	private System.Nullable<int> _Id_book;
	
	private System.Nullable<int> _Id_room;
	
	private EntityRef<Book> _Book;
	
	private EntityRef<Room> _Room;
	
	private EntityRef<Read_copy> _Read_copy;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnId_bookChanging(System.Nullable<int> value);
    partial void OnId_bookChanged();
    partial void OnId_roomChanging(System.Nullable<int> value);
    partial void OnId_roomChanged();
    #endregion
	
	public Book_copy()
	{
		this._Book = default(EntityRef<Book>);
		this._Room = default(EntityRef<Room>);
		this._Read_copy = default(EntityRef<Read_copy>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_Status", DbType="Int")]
	public System.Nullable<int> Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_book", Storage="_Id_book", DbType="Int")]
	public System.Nullable<int> Id_book
	{
		get
		{
			return this._Id_book;
		}
		set
		{
			if ((this._Id_book != value))
			{
				this.OnId_bookChanging(value);
				this.SendPropertyChanging();
				this._Id_book = value;
				this.SendPropertyChanged("Id_book");
				this.OnId_bookChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_room", Storage="_Id_room", DbType="Int")]
	public System.Nullable<int> Id_room
	{
		get
		{
			return this._Id_room;
		}
		set
		{
			if ((this._Id_room != value))
			{
				this.OnId_roomChanging(value);
				this.SendPropertyChanging();
				this._Id_room = value;
				this.SendPropertyChanged("Id_room");
				this.OnId_roomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__book_copy__ID_bo__59FA5E80", Storage="_Book", ThisKey="Id_book", OtherKey="Id", IsForeignKey=true)]
	public Book Book
	{
		get
		{
			return this._Book.Entity;
		}
		set
		{
			Book previousValue = this._Book.Entity;
			if (((previousValue != value) 
						|| (this._Book.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Book.Entity = null;
					previousValue.Book_copies.Remove(this);
				}
				this._Book.Entity = value;
				if ((value != null))
				{
					value.Book_copies.Add(this);
					this._Id_book = value.Id;
				}
				else
				{
					this._Id_book = default(Nullable<int>);
				}
				this.SendPropertyChanged("Book");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__book_copy__ID_ro__5AEE82B9", Storage="_Room", ThisKey="Id_room", OtherKey="Id", IsForeignKey=true)]
	public Room Room
	{
		get
		{
			return this._Room.Entity;
		}
		set
		{
			Room previousValue = this._Room.Entity;
			if (((previousValue != value) 
						|| (this._Room.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Room.Entity = null;
					previousValue.Book_copies.Remove(this);
				}
				this._Room.Entity = value;
				if ((value != null))
				{
					value.Book_copies.Add(this);
					this._Id_room = value.Id;
				}
				else
				{
					this._Id_room = default(Nullable<int>);
				}
				this.SendPropertyChanged("Room");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__read_copy__ID_co__6FE99F9F", Storage="_Read_copy", ThisKey="Id", OtherKey="Id_copy", IsUnique=true, IsForeignKey=false, DeleteRule="NO ACTION")]
	public Read_copy Read_copy
	{
		get
		{
			return this._Read_copy.Entity;
		}
		set
		{
			Read_copy previousValue = this._Read_copy.Entity;
			if (((previousValue != value) 
						|| (this._Read_copy.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Read_copy.Entity = null;
					previousValue.Book_copy = null;
				}
				this._Read_copy.Entity = value;
				if ((value != null))
				{
					value.Book_copy = this;
				}
				this.SendPropertyChanged("Read_copy");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.read_copy")]
public partial class Read_copy : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.DateTime _Data_pin;
	
	private System.Nullable<int> _Id_copy;
	
	private System.Nullable<int> _Id_reader;
	
	private EntityRef<Book_copy> _Book_copy;
	
	private EntityRef<Reader> _Reader;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnData_pinChanging(System.DateTime value);
    partial void OnData_pinChanged();
    partial void OnId_copyChanging(System.Nullable<int> value);
    partial void OnId_copyChanged();
    partial void OnId_readerChanging(System.Nullable<int> value);
    partial void OnId_readerChanged();
    #endregion
	
	public Read_copy()
	{
		this._Book_copy = default(EntityRef<Book_copy>);
		this._Reader = default(EntityRef<Reader>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_pin", Storage="_Data_pin", DbType="Date NOT NULL")]
	public System.DateTime Data_pin
	{
		get
		{
			return this._Data_pin;
		}
		set
		{
			if ((this._Data_pin != value))
			{
				this.OnData_pinChanging(value);
				this.SendPropertyChanging();
				this._Data_pin = value;
				this.SendPropertyChanged("Data_pin");
				this.OnData_pinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_copy", Storage="_Id_copy", DbType="Int")]
	public System.Nullable<int> Id_copy
	{
		get
		{
			return this._Id_copy;
		}
		set
		{
			if ((this._Id_copy != value))
			{
				this.OnId_copyChanging(value);
				this.SendPropertyChanging();
				this._Id_copy = value;
				this.SendPropertyChanged("Id_copy");
				this.OnId_copyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_reader", Storage="_Id_reader", DbType="Int")]
	public System.Nullable<int> Id_reader
	{
		get
		{
			return this._Id_reader;
		}
		set
		{
			if ((this._Id_reader != value))
			{
				this.OnId_readerChanging(value);
				this.SendPropertyChanging();
				this._Id_reader = value;
				this.SendPropertyChanged("Id_reader");
				this.OnId_readerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__read_copy__ID_co__6FE99F9F", Storage="_Book_copy", ThisKey="Id_copy", OtherKey="Id", IsForeignKey=true)]
	public Book_copy Book_copy
	{
		get
		{
			return this._Book_copy.Entity;
		}
		set
		{
			Book_copy previousValue = this._Book_copy.Entity;
			if (((previousValue != value) 
						|| (this._Book_copy.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Book_copy.Entity = null;
					previousValue.Read_copy = null;
				}
				this._Book_copy.Entity = value;
				if ((value != null))
				{
					value.Read_copy = this;
					this._Id_copy = value.Id;
				}
				else
				{
					this._Id_copy = default(Nullable<int>);
				}
				this.SendPropertyChanged("Book_copy");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__read_copy__ID_re__70DDC3D8", Storage="_Reader", ThisKey="Id_reader", OtherKey="Id", IsForeignKey=true)]
	public Reader Reader
	{
		get
		{
			return this._Reader.Entity;
		}
		set
		{
			Reader previousValue = this._Reader.Entity;
			if (((previousValue != value) 
						|| (this._Reader.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Reader.Entity = null;
					previousValue.Read_copies.Remove(this);
				}
				this._Reader.Entity = value;
				if ((value != null))
				{
					value.Read_copies.Add(this);
					this._Id_reader = value.Id;
				}
				else
				{
					this._Id_reader = default(Nullable<int>);
				}
				this.SendPropertyChanged("Reader");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reader")]
public partial class Reader : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _First_name;
	
	private string _Surname;
	
	private System.Nullable<int> _Phone;
	
	private System.Nullable<int> _Id_room;
	
	private EntitySet<Read_copy> _Read_copies;
	
	private EntityRef<Room> _Room;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirst_nameChanging(string value);
    partial void OnFirst_nameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnPhoneChanging(System.Nullable<int> value);
    partial void OnPhoneChanged();
    partial void OnId_roomChanging(System.Nullable<int> value);
    partial void OnId_roomChanged();
    #endregion
	
	public Reader()
	{
		this._Read_copies = new EntitySet<Read_copy>(new Action<Read_copy>(this.attach_Read_copies), new Action<Read_copy>(this.detach_Read_copies));
		this._Room = default(EntityRef<Room>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="first_name", Storage="_First_name", DbType="VarChar(200)")]
	public string First_name
	{
		get
		{
			return this._First_name;
		}
		set
		{
			if ((this._First_name != value))
			{
				this.OnFirst_nameChanging(value);
				this.SendPropertyChanging();
				this._First_name = value;
				this.SendPropertyChanged("First_name");
				this.OnFirst_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="surname", Storage="_Surname", DbType="VarChar(200)")]
	public string Surname
	{
		get
		{
			return this._Surname;
		}
		set
		{
			if ((this._Surname != value))
			{
				this.OnSurnameChanging(value);
				this.SendPropertyChanging();
				this._Surname = value;
				this.SendPropertyChanged("Surname");
				this.OnSurnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="phone", Storage="_Phone", DbType="Int")]
	public System.Nullable<int> Phone
	{
		get
		{
			return this._Phone;
		}
		set
		{
			if ((this._Phone != value))
			{
				this.OnPhoneChanging(value);
				this.SendPropertyChanging();
				this._Phone = value;
				this.SendPropertyChanged("Phone");
				this.OnPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_room", Storage="_Id_room", DbType="Int")]
	public System.Nullable<int> Id_room
	{
		get
		{
			return this._Id_room;
		}
		set
		{
			if ((this._Id_room != value))
			{
				this.OnId_roomChanging(value);
				this.SendPropertyChanging();
				this._Id_room = value;
				this.SendPropertyChanged("Id_room");
				this.OnId_roomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__read_copy__ID_re__70DDC3D8", Storage="_Read_copies", ThisKey="Id", OtherKey="Id_reader", DeleteRule="NO ACTION")]
	public EntitySet<Read_copy> Read_copies
	{
		get
		{
			return this._Read_copies;
		}
		set
		{
			this._Read_copies.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__reader__ID_room__5629CD9C", Storage="_Room", ThisKey="Id_room", OtherKey="Id", IsForeignKey=true)]
	public Room Room
	{
		get
		{
			return this._Room.Entity;
		}
		set
		{
			Room previousValue = this._Room.Entity;
			if (((previousValue != value) 
						|| (this._Room.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Room.Entity = null;
					previousValue.Readers.Remove(this);
				}
				this._Room.Entity = value;
				if ((value != null))
				{
					value.Readers.Add(this);
					this._Id_room = value.Id;
				}
				else
				{
					this._Id_room = default(Nullable<int>);
				}
				this.SendPropertyChanged("Room");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Read_copies(Read_copy entity)
	{
		this.SendPropertyChanging();
		entity.Reader = this;
	}
	
	private void detach_Read_copies(Read_copy entity)
	{
		this.SendPropertyChanging();
		entity.Reader = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.room")]
public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Room_name;
	
	private System.Nullable<int> _Roominess;
	
	private EntitySet<Book_copy> _Book_copies;
	
	private EntitySet<Reader> _Readers;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRoom_nameChanging(string value);
    partial void OnRoom_nameChanged();
    partial void OnRoominessChanging(System.Nullable<int> value);
    partial void OnRoominessChanged();
    #endregion
	
	public Room()
	{
		this._Book_copies = new EntitySet<Book_copy>(new Action<Book_copy>(this.attach_Book_copies), new Action<Book_copy>(this.detach_Book_copies));
		this._Readers = new EntitySet<Reader>(new Action<Reader>(this.attach_Readers), new Action<Reader>(this.detach_Readers));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="room_name", Storage="_Room_name", DbType="VarChar(200)")]
	public string Room_name
	{
		get
		{
			return this._Room_name;
		}
		set
		{
			if ((this._Room_name != value))
			{
				this.OnRoom_nameChanging(value);
				this.SendPropertyChanging();
				this._Room_name = value;
				this.SendPropertyChanged("Room_name");
				this.OnRoom_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="roominess", Storage="_Roominess", DbType="Int")]
	public System.Nullable<int> Roominess
	{
		get
		{
			return this._Roominess;
		}
		set
		{
			if ((this._Roominess != value))
			{
				this.OnRoominessChanging(value);
				this.SendPropertyChanging();
				this._Roominess = value;
				this.SendPropertyChanged("Roominess");
				this.OnRoominessChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__book_copy__ID_ro__5AEE82B9", Storage="_Book_copies", ThisKey="Id", OtherKey="Id_room", DeleteRule="NO ACTION")]
	public EntitySet<Book_copy> Book_copies
	{
		get
		{
			return this._Book_copies;
		}
		set
		{
			this._Book_copies.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FK__reader__ID_room__5629CD9C", Storage="_Readers", ThisKey="Id", OtherKey="Id_room", DeleteRule="NO ACTION")]
	public EntitySet<Reader> Readers
	{
		get
		{
			return this._Readers;
		}
		set
		{
			this._Readers.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Book_copies(Book_copy entity)
	{
		this.SendPropertyChanging();
		entity.Room = this;
	}
	
	private void detach_Book_copies(Book_copy entity)
	{
		this.SendPropertyChanging();
		entity.Room = null;
	}
	
	private void attach_Readers(Reader entity)
	{
		this.SendPropertyChanging();
		entity.Room = this;
	}
	
	private void detach_Readers(Reader entity)
	{
		this.SendPropertyChanging();
		entity.Room = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.status")]
public partial class Status : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Status1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStatus1Changing(string value);
    partial void OnStatus1Changed();
    #endregion
	
	public Status()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_Status1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Status1
	{
		get
		{
			return this._Status1;
		}
		set
		{
			if ((this._Status1 != value))
			{
				this.OnStatus1Changing(value);
				this.SendPropertyChanging();
				this._Status1 = value;
				this.SendPropertyChanged("Status1");
				this.OnStatus1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class Find_readers_bookResult
{
	
	private string _Title;
	
	public Find_readers_bookResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="title", Storage="_Title", DbType="VarChar(200)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this._Title = value;
			}
		}
	}
}

public partial class Sp_helpdiagramdefinitionResult
{
	
	private System.Nullable<int> _Version;
	
	private System.Data.Linq.Binary _Definition;
	
	public Sp_helpdiagramdefinitionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="version", Storage="_Version", DbType="Int")]
	public System.Nullable<int> Version
	{
		get
		{
			return this._Version;
		}
		set
		{
			if ((this._Version != value))
			{
				this._Version = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="definition", Storage="_Definition", DbType="VarBinary(MAX)", CanBeNull=true)]
	public System.Data.Linq.Binary Definition
	{
		get
		{
			return this._Definition;
		}
		set
		{
			if ((this._Definition != value))
			{
				this._Definition = value;
			}
		}
	}
}

public partial class Sp_helpdiagramsResult
{
	
	private string _Database;
	
	private string _Name;
	
	private System.Nullable<int> _ID;
	
	private string _Owner;
	
	private System.Nullable<int> _OwnerID;
	
	public Sp_helpdiagramsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Database", DbType="NVarChar(128)")]
	public string Database
	{
		get
		{
			return this._Database;
		}
		set
		{
			if ((this._Database != value))
			{
				this._Database = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(128)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
	public System.Nullable<int> ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner", DbType="NVarChar(128)")]
	public string Owner
	{
		get
		{
			return this._Owner;
		}
		set
		{
			if ((this._Owner != value))
			{
				this._Owner = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="Int")]
	public System.Nullable<int> OwnerID
	{
		get
		{
			return this._OwnerID;
		}
		set
		{
			if ((this._OwnerID != value))
			{
				this._OwnerID = value;
			}
		}
	}
}
#pragma warning restore 1591
